⚡ 유저의 상태를 저장할 UserState를 만들어 최초 선택 후, 바로 HomeView로 진입하도록 합니다.
RaniPaper/RaniPaper pull request #28
Opened 2022-12-05 15:36 UTC by youn9k

### 배경
- "비챤", "이파리" 선택 화면에서 최초 선택한 다음부턴 바로 런치스크린, 홈뷰로 진입되도록 구현해야 했습니다.
- 유저의 상태에 따라 기능을 Disable/ Enable 할 수 있도록 해야 했습니다.

### 작업 내용
- 원하는 뷰에서 유저의 상태에 따라 분기 처리할 수 있도록 하기 위해, MainViewModel 에 종속되지 않고 글로벌하게 접근할 수있도록,
UserState 클래스를 **싱글톤**으로 선언하여 **main 엔트리 포인트에서 최초 생성 후** **EnvironmentObject** 로 각 뷰에게 전달합니다.
- 유저디폴트를 통해 유저의 상태를 저장하고 불러오는 update(), fetch() 메소드를 추가합니다.
-  MainViewModel 에서 사용중이던 LockState 를 UserType 으로 변경합니다.

### 참고 영상
- 최초 '이파리' 선택 후 앱 재실행 시 바로 런치스크린 - 홈뷰로 이동하는 모습

https://user-images.githubusercontent.com/60254939/205677523-70d4e3ed-c646-444a-b4c5-c448a86d1470.mov

2022-12-05 15:48 UTC, JiDongseok11 approved these changes
확인했습니다!
편의성이 더 좋은 것 같지는 않지만.. MyUserDefaults로 유저 디폴트 매니저 만들어 놓긴 했습니다..!

2022-12-06 03:35 UTC, yongbeomkwak requested changes
이파리를 골라도 처음에 런치스크린을 뜨긴 떠야할 것 같아요
이파리 전용 런치스크린 이미지와 문구를 제작한다고 들었던 것 같아요!

2022-12-06 05:04 UTC, youn9k commented
> 이파리를 골라도 처음에 런치스크린을 뜨긴 떠야할 것 같아요 이파리 전용 런치스크린 이미지와 문구를 제작한다고 들었던 것 같아요!

확인해보니 영상찍는다고 임시로 로그아웃버튼을 만든거라 MainView 에 isLoading을 초기화 안해줘서 그런거였네요
앱 진입할때마다 이파리면 이파리 런치스크린, 비챤님이면 비챤님 런치스크린 항상 뜹니다

https://user-images.githubusercontent.com/60254939/205820573-bc88ff8a-8440-4276-8946-230663a9b095.mov

2022-12-06 05:07 UTC, yongbeomkwak commented
앗 그렀군요 확인했습니다 수고하셨습니다!

2022-12-06 05:07 UTC, yongbeomkwak approved these changes

2022-12-06 05:08 UTC, merged